### ISSUE TITLE
Fix getBlockCount

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-server#68]
```
express deprecated res.send(status): Use res.sendStatus(status) instead src/route/api.js:21:30
(node:9444) UnhandledPromiseRejectionWarning: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 69075
    at ServerResponse.writeHead (_http_server.js:193:11)
    at ServerResponse._implicitHeader (_http_server.js:184:8)
    at ServerResponse.end (_http_outgoing.js:768:10)
    at ServerResponse.res.end (/root/bodhi-server/node_modules/express-winston/index.js:239:17)
    at ServerResponse.send (/root/bodhi-server/node_modules/express/lib/response.js:221:10)
    at onRequestSuccess (/root/bodhi-server/src/route/api.js:21:30)
    at Blockchain.getBlockCount.then (/root/bodhi-server/src/route/api.js:166:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by dwalintukan** [comment]
#82

**Comment by dwalintukan** [comment]
#81
